'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AppResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.AppResource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attributes.
        '''</summary>
        Friend Shared ReadOnly Property Atributy() As String
            Get
                Return ResourceManager.GetString("Atributy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Knowladge bases on server.
        '''</summary>
        Friend Shared ReadOnly Property bazeZnalostiDostupneNaServeru() As String
            Get
                Return ResourceManager.GetString("bazeZnalostiDostupneNaServeru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property dalsiNastaveni() As String
            Get
                Return ResourceManager.GetString("dalsiNastaveni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to date.
        '''</summary>
        Friend Shared ReadOnly Property datumVytvoreni() As String
            Get
                Return ResourceManager.GetString("datumVytvoreni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dialog.
        '''</summary>
        Friend Shared ReadOnly Property dialog() As String
            Get
                Return ResourceManager.GetString("dialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lower limit.
        '''</summary>
        Friend Shared ReadOnly Property DolniMez() As String
            Get
                Return ResourceManager.GetString("DolniMez", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to questionnaire.
        '''</summary>
        Friend Shared ReadOnly Property dotaznik() As String
            Get
                Return ResourceManager.GetString("dotaznik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to questionnaire with dialog.
        '''</summary>
        Friend Shared ReadOnly Property dotaznikSDialogem() As String
            Get
                Return ResourceManager.GetString("dotaznikSDialogem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to expert.
        '''</summary>
        Friend Shared ReadOnly Property expert() As String
            Get
                Return ResourceManager.GetString("expert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global properties.
        '''</summary>
        Friend Shared ReadOnly Property GlobalniParametry() As String
            Get
                Return ResourceManager.GetString("GlobalniParametry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value is out of range!.
        '''</summary>
        Friend Shared ReadOnly Property HodnotaJeMimoRozsah() As String
            Get
                Return ResourceManager.GetString("HodnotaJeMimoRozsah", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value doesn`t exist!.
        '''</summary>
        Friend Shared ReadOnly Property HodnotaNeexistuje() As String
            Get
                Return ResourceManager.GetString("HodnotaNeexistuje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value cant`t be read!.
        '''</summary>
        Friend Shared ReadOnly Property HodnotuSeNepodariloNacist() As String
            Get
                Return ResourceManager.GetString("HodnotuSeNepodariloNacist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upper limit.
        '''</summary>
        Friend Shared ReadOnly Property HorniMez() As String
            Get
                Return ResourceManager.GetString("HorniMez", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information about knowladge base.
        '''</summary>
        Friend Shared ReadOnly Property informaceOBaziZnalosti() As String
            Get
                Return ResourceManager.GetString("informaceOBaziZnalosti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integrity constraints.
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Irrelevant.
        '''</summary>
        Friend Shared ReadOnly Property Irelevantni() As String
            Get
                Return ResourceManager.GetString("Irelevantni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Česky.
        '''</summary>
        Friend Shared ReadOnly Property jazyk() As String
            Get
                Return ResourceManager.GetString("jazyk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certainly yes.
        '''</summary>
        Friend Shared ReadOnly Property JisteAno() As String
            Get
                Return ResourceManager.GetString("JisteAno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certainly no.
        '''</summary>
        Friend Shared ReadOnly Property JisteNe() As String
            Get
                Return ResourceManager.GetString("JisteNe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contexts.
        '''</summary>
        Friend Shared ReadOnly Property Kontexty() As String
            Get
                Return ResourceManager.GetString("Kontexty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check knowladge base.
        '''</summary>
        Friend Shared ReadOnly Property kontrolaBZ() As String
            Get
                Return ResourceManager.GetString("kontrolaBZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consult.
        '''</summary>
        Friend Shared ReadOnly Property Konzultuj() As String
            Get
                Return ResourceManager.GetString("Konzultuj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check KB.
        '''</summary>
        Friend Shared ReadOnly Property menu_kontrolaBZ() As String
            Get
                Return ResourceManager.GetString("menu_kontrolaBZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consultation.
        '''</summary>
        Friend Shared ReadOnly Property menu_konzultace() As String
            Get
                Return ResourceManager.GetString("menu_konzultace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New consultation.
        '''</summary>
        Friend Shared ReadOnly Property menu_novaKonzultace() As String
            Get
                Return ResourceManager.GetString("menu_novaKonzultace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove actual base.
        '''</summary>
        Friend Shared ReadOnly Property menu_odstranitNahranouBZ() As String
            Get
                Return ResourceManager.GetString("menu_odstranitNahranouBZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue to consult.
        '''</summary>
        Friend Shared ReadOnly Property menu_pokracovatVKonzultaci() As String
            Get
                Return ResourceManager.GetString("menu_pokracovatVKonzultaci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Statistics.
        '''</summary>
        Friend Shared ReadOnly Property menu_statistiky() As String
            Get
                Return ResourceManager.GetString("menu_statistiky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Knowladge base.
        '''</summary>
        Friend Shared ReadOnly Property menu_vypisBZ() As String
            Get
                Return ResourceManager.GetString("menu_vypisBZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of cases.
        '''</summary>
        Friend Shared ReadOnly Property menu_vypisCBR() As String
            Get
                Return ResourceManager.GetString("menu_vypisCBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surce code.
        '''</summary>
        Friend Shared ReadOnly Property menu_vypisZdrojovehoKodu() As String
            Get
                Return ResourceManager.GetString("menu_vypisZdrojovehoKodu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load answers from file:.
        '''</summary>
        Friend Shared ReadOnly Property NacistOdpovediZeSouboru() As String
            Get
                Return ResourceManager.GetString("NacistOdpovediZeSouboru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load.
        '''</summary>
        Friend Shared ReadOnly Property Nahraj() As String
            Get
                Return ResourceManager.GetString("Nahraj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigation.
        '''</summary>
        Friend Shared ReadOnly Property Navigace() As String
            Get
                Return ResourceManager.GetString("Navigace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property Nevim() As String
            Get
                Return ResourceManager.GetString("Nevim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend Shared ReadOnly Property Odeslat() As String
            Get
                Return ResourceManager.GetString("Odeslat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property popis() As String
            Get
                Return ResourceManager.GetString("popis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En - Byla porušena tato integritní omezení.
        '''</summary>
        Friend Shared ReadOnly Property PorusenaIntOm() As String
            Get
                Return ResourceManager.GetString("PorusenaIntOm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rules.
        '''</summary>
        Friend Shared ReadOnly Property Pravidla() As String
            Get
                Return ResourceManager.GetString("Pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add to loaded KB.
        '''</summary>
        Friend Shared ReadOnly Property Pridej() As String
            Get
                Return ResourceManager.GetString("Pridej", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Case.
        '''</summary>
        Friend Shared ReadOnly Property Pripad() As String
            Get
                Return ResourceManager.GetString("Pripad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Case base reasoning.
        '''</summary>
        Friend Shared ReadOnly Property PripadoveUsuzovani() As String
            Get
                Return ResourceManager.GetString("PripadoveUsuzovani", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cases.
        '''</summary>
        Friend Shared ReadOnly Property Pripady() As String
            Get
                Return ResourceManager.GetString("Pripady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Answering mode.
        '''</summary>
        Friend Shared ReadOnly Property rezimKonzultace() As String
            Get
                Return ResourceManager.GetString("rezimKonzultace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weight range.
        '''</summary>
        Friend Shared ReadOnly Property RozsahVah() As String
            Get
                Return ResourceManager.GetString("RozsahVah", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort by.
        '''</summary>
        Friend Shared ReadOnly Property SetriditDle() As String
            Get
                Return ResourceManager.GetString("SetriditDle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to name.
        '''</summary>
        Friend Shared ReadOnly Property SetriditDleJmena() As String
            Get
                Return ResourceManager.GetString("SetriditDleJmena", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to maximal weight.
        '''</summary>
        Friend Shared ReadOnly Property SetriditDleMaximalniVahy() As String
            Get
                Return ResourceManager.GetString("SetriditDleMaximalniVahy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minimal weight.
        '''</summary>
        Friend Shared ReadOnly Property SetriditDleMinimalniVahy() As String
            Get
                Return ResourceManager.GetString("SetriditDleMinimalniVahy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Storage of cases loaded.
        '''</summary>
        Friend Shared ReadOnly Property SkladPripaduLoaded() As String
            Get
                Return ResourceManager.GetString("SkladPripaduLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to change.
        '''</summary>
        Friend Shared ReadOnly Property upravit() As String
            Get
                Return ResourceManager.GetString("upravit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change answers.
        '''</summary>
        Friend Shared ReadOnly Property UpravitOdpovedi() As String
            Get
                Return ResourceManager.GetString("UpravitOdpovedi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weight is out of range!.
        '''</summary>
        Friend Shared ReadOnly Property VahaJeMimoRozsah() As String
            Get
                Return ResourceManager.GetString("VahaJeMimoRozsah", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weight cant`t be read!.
        '''</summary>
        Friend Shared ReadOnly Property VahuSeNepodariloNacist() As String
            Get
                Return ResourceManager.GetString("VahuSeNepodariloNacist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your knowladge base.
        '''</summary>
        Friend Shared ReadOnly Property vlastniBazeZnalosti() As String
            Get
                Return ResourceManager.GetString("vlastniBazeZnalosti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All propositions.
        '''</summary>
        Friend Shared ReadOnly Property VsechnyVyroky() As String
            Get
                Return ResourceManager.GetString("VsechnyVyroky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose knowladge base.
        '''</summary>
        Friend Shared ReadOnly Property vyberteBaziZnalosti() As String
            Get
                Return ResourceManager.GetString("vyberteBaziZnalosti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vyberteSkladPripadu.
        '''</summary>
        Friend Shared ReadOnly Property vyberteSkladPripadu() As String
            Get
                Return ResourceManager.GetString("vyberteSkladPripadu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List of knowladge base.
        '''</summary>
        Friend Shared ReadOnly Property VypisBazeZnalosti() As String
            Get
                Return ResourceManager.GetString("VypisBazeZnalosti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source code.
        '''</summary>
        Friend Shared ReadOnly Property VypisZdrojovehoKodu() As String
            Get
                Return ResourceManager.GetString("VypisZdrojovehoKodu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results.
        '''</summary>
        Friend Shared ReadOnly Property Vysledky() As String
            Get
                Return ResourceManager.GetString("Vysledky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance.
        '''</summary>
        Friend Shared ReadOnly Property Vzdalenost() As String
            Get
                Return ResourceManager.GetString("Vzdalenost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check.
        '''</summary>
        Friend Shared ReadOnly Property Zkontroluj() As String
            Get
                Return ResourceManager.GetString("Zkontroluj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Knowladge engineer.
        '''</summary>
        Friend Shared ReadOnly Property znalostniInzenyr() As String
            Get
                Return ResourceManager.GetString("znalostniInzenyr", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
