'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Texty_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NestBase.Texty_en", GetType(Texty_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apriori.
        '''</summary>
        Friend Shared ReadOnly Property Apriori() As String
            Get
                Return ResourceManager.GetString("Apriori", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attribute.
        '''</summary>
        Friend Shared ReadOnly Property Atribut() As String
            Get
                Return ResourceManager.GetString("Atribut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání id atributu z xml.
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Chyba_pri_nacitani_id_atributu_z_xml() As String
            Get
                Return ResourceManager.GetString("Atribut_Chyba_pri_nacitani_id_atributu_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání zdroje!.
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Chyba_pri_nacitani_zdroje() As String
            Get
                Return ResourceManager.GetString("Atribut_Chyba_pri_nacitani_zdroje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání zdrojů atributu z XML.
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Chyba_pri_nacitani_zdroju_atributu_z_XML() As String
            Get
                Return ResourceManager.GetString("Atribut_Chyba_pri_nacitani_zdroju_atributu_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v atributu .
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Chyba_pri_SaveToXML_v_atributu() As String
            Get
                Return ResourceManager.GetString("Atribut_Chyba_pri_SaveToXML_v_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu atributu .
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Chyba_pri_tvorbe_vypisu_atributu() As String
            Get
                Return ResourceManager.GetString("Atribut_Chyba_pri_tvorbe_vypisu_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při určování pozice atributu .
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Chyba_pri_urcovani_pozice_atributu() As String
            Get
                Return ResourceManager.GetString("Atribut_Chyba_pri_urcovani_pozice_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Výroky mají různé pozice pro atribut .
        '''</summary>
        Friend Shared ReadOnly Property Atribut_Vyroky_maji_ruzne_pozice_pro_atribut() As String
            Get
                Return ResourceManager.GetString("Atribut_Vyroky_maji_ruzne_pozice_pro_atribut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání binarniho atributu z xml.
        '''</summary>
        Friend Shared ReadOnly Property AtributBinary_Chyba_pri_nacitani_binarniho_atributu_z_xml() As String
            Get
                Return ResourceManager.GetString("AtributBinary_Chyba_pri_nacitani_binarniho_atributu_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání odpovědi z xml u atributu: .
        '''</summary>
        Friend Shared ReadOnly Property AtributBinary_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributBinary_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při počítání váhy u atributu .
        '''</summary>
        Friend Shared ReadOnly Property AtributBinary_Chyba_pri_pocitani_vahy_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributBinary_Chyba_pri_pocitani_vahy_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v atributu binary .
        '''</summary>
        Friend Shared ReadOnly Property AtributBinary_Chyba_pri_SaveToXML_v_atributu_binary() As String
            Get
                Return ResourceManager.GetString("AtributBinary_Chyba_pri_SaveToXML_v_atributu_binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vkládání váhy u atributu: .
        '''</summary>
        Friend Shared ReadOnly Property AtributBinary_Chyba_pri_Vkladani_vahy_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributBinary_Chyba_pri_Vkladani_vahy_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání multiple atributu z xml.
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Chyba_pri_nacitani_multiple_atributu_z_xml() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Chyba_pri_nacitani_multiple_atributu_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání odpovědi z xml u atributu: .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při počítání váhy u atributu .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Chyba_pri_pocitani_vahy_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Chyba_pri_pocitani_vahy_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v atributu multiple .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Chyba_pri_SaveToXML_v_atributu_multiple() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Chyba_pri_SaveToXML_v_atributu_multiple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vkládání váhy .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Chyba_pri_vkladani_vahy() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Chyba_pri_vkladani_vahy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hodnota odpovědi neexistuje pro atribut: .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Hodnota_odpovedi_neexistuje_pro_atribut() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Hodnota_odpovedi_neexistuje_pro_atribut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  to attribute .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_k_atributu() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_k_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nepodařilo se načíst hodnotu odpovědi pro atribut: .
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Nepodarilo_se_nacist_hodnotu_odpovedi_pro_atribut() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Nepodarilo_se_nacist_hodnotu_odpovedi_pro_atribut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set weights have not the right number!.
        '''</summary>
        Friend Shared ReadOnly Property AtributMultiple_Zadane_vahy_nemaji_spravny_pocet() As String
            Get
                Return ResourceManager.GetString("AtributMultiple_Zadane_vahy_nemaji_spravny_pocet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání numerického atributu z xml.
        '''</summary>
        Friend Shared ReadOnly Property AtributNumeric_Chyba_pri_nacitani_numeric_atributu_z_xml() As String
            Get
                Return ResourceManager.GetString("AtributNumeric_Chyba_pri_nacitani_numeric_atributu_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání odpovědí z xml u atributu: .
        '''</summary>
        Friend Shared ReadOnly Property AtributNumeric_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributNumeric_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání zdroje!.
        '''</summary>
        Friend Shared ReadOnly Property AtributNumeric_Chyba_pri_nacitani_zdroje() As String
            Get
                Return ResourceManager.GetString("AtributNumeric_Chyba_pri_nacitani_zdroje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při počítání váhy u atributu .
        '''</summary>
        Friend Shared ReadOnly Property AtributNumeric_Chyba_pri_pocitani_vahy_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributNumeric_Chyba_pri_pocitani_vahy_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v atributu .
        '''</summary>
        Friend Shared ReadOnly Property AtributNumeric_Chyba_pri_SaveToXML_v_atributu() As String
            Get
                Return ResourceManager.GetString("AtributNumeric_Chyba_pri_SaveToXML_v_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v atributu numeric .
        '''</summary>
        Friend Shared ReadOnly Property AtributNumeric_Chyba_pri_SaveToXML_v_atributu_binary() As String
            Get
                Return ResourceManager.GetString("AtributNumeric_Chyba_pri_SaveToXML_v_atributu_binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání odpovědi z xml u atributu: .
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Chyba_pri_nacitani_odpovedi_z_xml_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání single atributu z xml.
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Chyba_pri_nacitani_single_atributu_z_xml() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Chyba_pri_nacitani_single_atributu_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při počítání váhy u atributu .
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Chyba_pri_pocitani_vahy_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Chyba_pri_pocitani_vahy_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v atributu single .
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Chyba_pri_SaveToXML_v_atributu_single() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Chyba_pri_SaveToXML_v_atributu_single", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vkládání váhy u atributu: .
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Chyba_pri_Vkladani_vahy_u_atributu() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Chyba_pri_Vkladani_vahy_u_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no value for attribute: .
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Hodnota_odpovedi_neexistuje_pro_atribut() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Hodnota_odpovedi_neexistuje_pro_atribut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can`t read the value for attribute: .
        '''</summary>
        Friend Shared ReadOnly Property AtributSingle_Nepodarilo_se_nacist_hodnotu_odpovedi_pro_atribut() As String
            Get
                Return ResourceManager.GetString("AtributSingle_Nepodarilo_se_nacist_hodnotu_odpovedi_pro_atribut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attributes.
        '''</summary>
        Friend Shared ReadOnly Property Atributy() As String
            Get
                Return ResourceManager.GetString("Atributy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při generování statistik.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_generovani_statistik() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_generovani_statistik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání atributů.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_nacitani_atributu() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_nacitani_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání globálních parametrů.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_nacitani_globalnich_parametru() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_nacitani_globalnich_parametru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání odpovědí z xml.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_nacitani_odpovedi_z_xml() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_nacitani_odpovedi_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování báze znalostí..
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_propojovani_baze() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_propojovani_baze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při ukládání apriori pravidel.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_ukladani_apriori_pravidel() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_ukladani_apriori_pravidel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při ukládání atributů.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_ukladani_atributu() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_ukladani_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při ukládání integritních omezení.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_ukladani_integritnich_omezeni() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_ukladani_integritnich_omezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při ukládání kompozicionálních pravidel.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_ukladani_kompozicionalnich_pravidel() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_ukladani_kompozicionalnich_pravidel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při ukládání kontextů.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_ukladani_kontextu() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_ukladani_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při ukládání logických pravidel.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_ukladani_logickeho_pravidel() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_ukladani_logickeho_pravidel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při uklání globálních parametrů.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Chyba_pri_uklani_globalnich_parametru() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Chyba_pri_uklani_globalnich_parametru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unexpected error.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Neocekavana_chyba() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Neocekavana_chyba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can`t read the xml document.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Nepodarilo_se_nacist_xml_dokument() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Nepodarilo_se_nacist_xml_dokument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can`t read the xml document with answers.
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Nepodarilo_se_nacist_xml_dokument_odpovedi() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Nepodarilo_se_nacist_xml_dokument_odpovedi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokus o načtení druhého atributu se stejným identifikátorem: .
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Pokus_o_nacteni_druheho_atributu() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Pokus_o_nacteni_druheho_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokus o načtení druhého integritniho omezeni se stejným identifikátorem: .
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Pokus_o_nacteni_druheho_integritniho_omezeni() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Pokus_o_nacteni_druheho_integritniho_omezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokus o načtení druhého kontextu se stejným identifikátorem: .
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Pokus_o_nacteni_druheho_kontextu() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Pokus_o_nacteni_druheho_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokus o načtení druhého pravidla se stejným identifikátorem: .
        '''</summary>
        Friend Shared ReadOnly Property BazeZnalosti_Pokus_o_nacteni_druheho_pravidla() As String
            Get
                Return ResourceManager.GetString("BazeZnalosti_Pokus_o_nacteni_druheho_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Báze znalostí obsahuje cyklus - výrok v cyklu: .
        '''</summary>
        Friend Shared ReadOnly Property BazeZnaloti_Baze_znalosti_obsahuje_cyklus() As String
            Get
                Return ResourceManager.GetString("BazeZnaloti_Baze_znalosti_obsahuje_cyklus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při počítání váhy závěru u cbr compositional.
        '''</summary>
        Friend Shared ReadOnly Property CbrUsuzovaniCompositional_Chyba_pri_pocitani_vahy_zaveru_u_cbr_compositional() As String
            Get
                Return ResourceManager.GetString("CbrUsuzovaniCompositional_Chyba_pri_pocitani_vahy_zaveru_u_cbr_compositional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při výpočtu vzdálenosti dvou výroků.
        '''</summary>
        Friend Shared ReadOnly Property CbrUsuzovaniCompositional_Chyba_pri_vypoctu_vzdalenosti_dvou_vyroku() As String
            Get
                Return ResourceManager.GetString("CbrUsuzovaniCompositional_Chyba_pri_vypoctu_vzdalenosti_dvou_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při výpočtu vzdálenosti případů.
        '''</summary>
        Friend Shared ReadOnly Property CbrUsuzovaniCompositional_Chyba_pri_vypoctu_vzdalenosti_pripadu() As String
            Get
                Return ResourceManager.GetString("CbrUsuzovaniCompositional_Chyba_pri_vypoctu_vzdalenosti_pripadu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property Celkem() As String
            Get
                Return ResourceManager.GetString("Celkem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Goal.
        '''</summary>
        Friend Shared ReadOnly Property Cil() As String
            Get
                Return ResourceManager.GetString("Cil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crisp lower.
        '''</summary>
        Friend Shared ReadOnly Property CrispLower() As String
            Get
                Return ResourceManager.GetString("CrispLower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crisp upper.
        '''</summary>
        Friend Shared ReadOnly Property CrispUpper() As String
            Get
                Return ResourceManager.GetString("CrispUpper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Others.
        '''</summary>
        Friend Shared ReadOnly Property Dalsi() As String
            Get
                Return ResourceManager.GetString("Dalsi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property Datum() As String
            Get
                Return ResourceManager.GetString("Datum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default weight.
        '''</summary>
        Friend Shared ReadOnly Property DefaultVaha() As String
            Get
                Return ResourceManager.GetString("DefaultVaha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Question.
        '''</summary>
        Friend Shared ReadOnly Property Dotaz() As String
            Get
                Return ResourceManager.GetString("Dotaz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to apriori.
        '''</summary>
        Friend Shared ReadOnly Property Enums_apriori() As String
            Get
                Return ResourceManager.GetString("Enums_apriori", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to binary.
        '''</summary>
        Friend Shared ReadOnly Property Enums_binary() As String
            Get
                Return ResourceManager.GetString("Enums_binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to final.
        '''</summary>
        Friend Shared ReadOnly Property Enums_final() As String
            Get
                Return ResourceManager.GetString("Enums_final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hybrid.
        '''</summary>
        Friend Shared ReadOnly Property Enums_hybridni() As String
            Get
                Return ResourceManager.GetString("Enums_hybridni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to compositional.
        '''</summary>
        Friend Shared ReadOnly Property Enums_kompozicionalni() As String
            Get
                Return ResourceManager.GetString("Enums_kompozicionalni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to logical.
        '''</summary>
        Friend Shared ReadOnly Property Enums_logical() As String
            Get
                Return ResourceManager.GetString("Enums_logical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to logical.
        '''</summary>
        Friend Shared ReadOnly Property Enums_logicke() As String
            Get
                Return ResourceManager.GetString("Enums_logicke", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to logical.
        '''</summary>
        Friend Shared ReadOnly Property Enums_logicky() As String
            Get
                Return ResourceManager.GetString("Enums_logicky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to max. length.
        '''</summary>
        Friend Shared ReadOnly Property Enums_maximalni_delka() As String
            Get
                Return ResourceManager.GetString("Enums_maximalni_delka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to min. length.
        '''</summary>
        Friend Shared ReadOnly Property Enums_minimalni_delka() As String
            Get
                Return ResourceManager.GetString("Enums_minimalni_delka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nominal set.
        '''</summary>
        Friend Shared ReadOnly Property Enums_multiple() As String
            Get
                Return ResourceManager.GetString("Enums_multiple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to neural.
        '''</summary>
        Friend Shared ReadOnly Property Enums_neuronovy() As String
            Get
                Return ResourceManager.GetString("Enums_neuronovy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to numeric.
        '''</summary>
        Friend Shared ReadOnly Property Enums_numeric() As String
            Get
                Return ResourceManager.GetString("Enums_numeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to from end.
        '''</summary>
        Friend Shared ReadOnly Property Enums_od_konce() As String
            Get
                Return ResourceManager.GetString("Enums_od_konce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to from begin.
        '''</summary>
        Friend Shared ReadOnly Property Enums_od_zacatku() As String
            Get
                Return ResourceManager.GetString("Enums_od_zacatku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to partial.
        '''</summary>
        Friend Shared ReadOnly Property Enums_partial() As String
            Get
                Return ResourceManager.GetString("Enums_partial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dočasný.
        '''</summary>
        Friend Shared ReadOnly Property Enums_provisional() As String
            Get
                Return ResourceManager.GetString("Enums_provisional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to nominal single.
        '''</summary>
        Friend Shared ReadOnly Property Enums_single() As String
            Get
                Return ResourceManager.GetString("Enums_single", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to standard.
        '''</summary>
        Friend Shared ReadOnly Property Enums_standardni() As String
            Get
                Return ResourceManager.GetString("Enums_standardni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to untuched.
        '''</summary>
        Friend Shared ReadOnly Property Enums_untouched() As String
            Get
                Return ResourceManager.GetString("Enums_untouched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to user.
        '''</summary>
        Friend Shared ReadOnly Property Enums_uzivatelska() As String
            Get
                Return ResourceManager.GetString("Enums_uzivatelska", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expert.
        '''</summary>
        Friend Shared ReadOnly Property Expert() As String
            Get
                Return ResourceManager.GetString("Expert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fuzzy lower.
        '''</summary>
        Friend Shared ReadOnly Property FuzzyLower() As String
            Get
                Return ResourceManager.GetString("FuzzyLower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fuzzy upper.
        '''</summary>
        Friend Shared ReadOnly Property Fuzzyupper() As String
            Get
                Return ResourceManager.GetString("Fuzzyupper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global properties.
        '''</summary>
        Friend Shared ReadOnly Property GlobalniParametry() As String
            Get
                Return ResourceManager.GetString("GlobalniParametry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global pririty.
        '''</summary>
        Friend Shared ReadOnly Property GlobalPriority() As String
            Get
                Return ResourceManager.GetString("GlobalPriority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id.
        '''</summary>
        Friend Shared ReadOnly Property id() As String
            Get
                Return ResourceManager.GetString("id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inference mechanism.
        '''</summary>
        Friend Shared ReadOnly Property InferencniMechanismus() As String
            Get
                Return ResourceManager.GetString("InferencniMechanismus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integrity constraints.
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání id integritniho omezeni z xml.
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni_Chyba_pri_nacitani_id_integritniho_omezeni_z_xml() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni_Chyba_pri_nacitani_id_integritniho_omezeni_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání integritního omezení z XML.
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni_Chyba_pri_nacitani_integritniho_omezeni_z_XML() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni_Chyba_pri_nacitani_integritniho_omezeni_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v integritním omezení .
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni_Chyba_pri_SaveToXML_v_integritnim_omezeni() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni_Chyba_pri_SaveToXML_v_integritnim_omezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování integritního omezení .
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni_Chyba_pri_vyhodnocovani_integritniho_omezeni() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni_Chyba_pri_vyhodnocovani_integritniho_omezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  : integrity constraint .
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni_integritni_omezeni() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni_integritni_omezeni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  : rule .
        '''</summary>
        Friend Shared ReadOnly Property IntegritniOmezeni_pravidlo() As String
            Get
                Return ResourceManager.GetString("IntegritniOmezeni_pravidlo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Knowladge engineer.
        '''</summary>
        Friend Shared ReadOnly Property Inzenyr() As String
            Get
                Return ResourceManager.GetString("Inzenyr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property Jmeno() As String
            Get
                Return ResourceManager.GetString("Jmeno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment.
        '''</summary>
        Friend Shared ReadOnly Property Komentar() As String
            Get
                Return ResourceManager.GetString("Komentar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání konjunkce z XML.
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Chyba_pri_nacitani_konjunkce_z_XML() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Chyba_pri_nacitani_konjunkce_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování kontextu .
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Chyba_pri_propojovani_kontextu() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Chyba_pri_propojovani_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování předpokladu u pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Chyba_pri_propojovani_predpokladu_u_pravidla() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Chyba_pri_propojovani_predpokladu_u_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v konjunkci.
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Chyba_pri_SaveToXML_v_konjunkci() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Chyba_pri_SaveToXML_v_konjunkci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu konjunkce.
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Chyba_pri_tvorbe_vypisu_konjunkce() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Chyba_pri_tvorbe_vypisu_konjunkce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování konjunkce backward.
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Chyba_pri_vyhodnocovani_konjunkce_backward() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Chyba_pri_vyhodnocovani_konjunkce_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prázdná konjunkce.
        '''</summary>
        Friend Shared ReadOnly Property Konjunkce_Prazdna_konjunkce() As String
            Get
                Return ResourceManager.GetString("Konjunkce_Prazdna_konjunkce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání id kontextu z xml.
        '''</summary>
        Friend Shared ReadOnly Property Kontext_Chyba_pri_nacitani_id_kontextu_z_xml() As String
            Get
                Return ResourceManager.GetString("Kontext_Chyba_pri_nacitani_id_kontextu_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání kontextu z XML.
        '''</summary>
        Friend Shared ReadOnly Property Kontext_Chyba_pri_nacitani_kontextu_z_XML() As String
            Get
                Return ResourceManager.GetString("Kontext_Chyba_pri_nacitani_kontextu_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování kontextu .
        '''</summary>
        Friend Shared ReadOnly Property Kontext_Chyba_pri_propojovani_kontextu() As String
            Get
                Return ResourceManager.GetString("Kontext_Chyba_pri_propojovani_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v kontextu .
        '''</summary>
        Friend Shared ReadOnly Property Kontext_Chyba_pri_SaveToXML_v_kontextu() As String
            Get
                Return ResourceManager.GetString("Kontext_Chyba_pri_SaveToXML_v_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu kontextu .
        '''</summary>
        Friend Shared ReadOnly Property Kontext_Chyba_pri_tvorbe_vypisu_kontextu() As String
            Get
                Return ResourceManager.GetString("Kontext_Chyba_pri_tvorbe_vypisu_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování kontextu backward.
        '''</summary>
        Friend Shared ReadOnly Property Kontext_Chyba_pri_vyhodnocovani_kontextu_backward() As String
            Get
                Return ResourceManager.GetString("Kontext_Chyba_pri_vyhodnocovani_kontextu_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  : context .
        '''</summary>
        Friend Shared ReadOnly Property Kontext_kontext() As String
            Get
                Return ResourceManager.GetString("Kontext_kontext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contexts.
        '''</summary>
        Friend Shared ReadOnly Property Kontexty() As String
            Get
                Return ResourceManager.GetString("Kontexty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování kontextu .
        '''</summary>
        Friend Shared ReadOnly Property Literal_Chyba_pri_propojovani_kontextu() As String
            Get
                Return ResourceManager.GetString("Literal_Chyba_pri_propojovani_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování předpokladu u pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Literal_Chyba_pri_propojovani_predpokladu_u_pravidla() As String
            Get
                Return ResourceManager.GetString("Literal_Chyba_pri_propojovani_predpokladu_u_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu literalu.
        '''</summary>
        Friend Shared ReadOnly Property Literal_Chyba_pri_tvorbe_vypisu_literalu() As String
            Get
                Return ResourceManager.GetString("Literal_Chyba_pri_tvorbe_vypisu_literalu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování literálu backward.
        '''</summary>
        Friend Shared ReadOnly Property Literal_Chyba_pri_vyhodnocovani_literalu_backward() As String
            Get
                Return ResourceManager.GetString("Literal_Chyba_pri_vyhodnocovani_literalu_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intermediate.
        '''</summary>
        Friend Shared ReadOnly Property Mezilehly() As String
            Get
                Return ResourceManager.GetString("Mezilehly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alone.
        '''</summary>
        Friend Shared ReadOnly Property Osamoceny() As String
            Get
                Return ResourceManager.GetString("Osamoceny", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property Popis() As String
            Get
                Return ResourceManager.GetString("Popis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global context threshold.
        '''</summary>
        Friend Shared ReadOnly Property PrahPlatnostiKontextu() As String
            Get
                Return ResourceManager.GetString("PrahPlatnostiKontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global condition threshold.
        '''</summary>
        Friend Shared ReadOnly Property PrahPlatnostiPredpokladu() As String
            Get
                Return ResourceManager.GetString("PrahPlatnostiPredpokladu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rules.
        '''</summary>
        Friend Shared ReadOnly Property Pravidla() As String
            Get
                Return ResourceManager.GetString("Pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při hledání závěru pro výrok .
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_Chyba_pri_hledani_zaveru_pro_vyrok() As String
            Get
                Return ResourceManager.GetString("Pravidlo_Chyba_pri_hledani_zaveru_pro_vyrok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání id pravidla z xml.
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_Chyba_pri_nacitani_id_pravidla_z_xml() As String
            Get
                Return ResourceManager.GetString("Pravidlo_Chyba_pri_nacitani_id_pravidla_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání pravidla z XML.
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_Chyba_pri_nacitani_pravidla_z_XML() As String
            Get
                Return ResourceManager.GetString("Pravidlo_Chyba_pri_nacitani_pravidla_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_Chyba_pri_propojovani_pravidla() As String
            Get
                Return ResourceManager.GetString("Pravidlo_Chyba_pri_propojovani_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_Chyba_pri_tvorbe_vypisu_pravidla() As String
            Get
                Return ResourceManager.GetString("Pravidlo_Chyba_pri_tvorbe_vypisu_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  : rule .
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_pravidlo() As String
            Get
                Return ResourceManager.GetString("Pravidlo_pravidlo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prázdný závěr pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_Prazdny_zaver_pravidla() As String
            Get
                Return ResourceManager.GetString("Pravidlo_Prazdny_zaver_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  u pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Pravidlo_u_pravidla() As String
            Get
                Return ResourceManager.GetString("Pravidlo_u_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při aplikování apriori pravidla backward .
        '''</summary>
        Friend Shared ReadOnly Property PravidloApriori_Chyba_pri_aplikovani_apriori_pravidla_backward() As String
            Get
                Return ResourceManager.GetString("PravidloApriori_Chyba_pri_aplikovani_apriori_pravidla_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání apriori pravidla z XML.
        '''</summary>
        Friend Shared ReadOnly Property PravidloApriori_Chyba_pri_nacitani_apriori_pravidla_z_XML() As String
            Get
                Return ResourceManager.GetString("PravidloApriori_Chyba_pri_nacitani_apriori_pravidla_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování apriori pravidla .
        '''</summary>
        Friend Shared ReadOnly Property PravidloApriori_Chyba_pri_propojovani_apriori_pravidla() As String
            Get
                Return ResourceManager.GetString("PravidloApriori_Chyba_pri_propojovani_apriori_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v apriori pravidlu .
        '''</summary>
        Friend Shared ReadOnly Property PravidloApriori_Chyba_při_SaveToXML_v_apriori_pravidlu() As String
            Get
                Return ResourceManager.GetString("PravidloApriori_Chyba_při_SaveToXML_v_apriori_pravidlu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu apriori pravidla .
        '''</summary>
        Friend Shared ReadOnly Property PravidloApriori_Chyba_pri_tvorbe_vypisu_apriori_pravidla() As String
            Get
                Return ResourceManager.GetString("PravidloApriori_Chyba_pri_tvorbe_vypisu_apriori_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při aplikování kompozicionálního pravidla backward .
        '''</summary>
        Friend Shared ReadOnly Property pravidloKompozicionalni_Chyba_pri_aplikovani_kompozicionalniho_pravidla_backward() As String
            Get
                Return ResourceManager.GetString("pravidloKompozicionalni_Chyba_pri_aplikovani_kompozicionalniho_pravidla_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání kompozicionálního pravidla z XML.
        '''</summary>
        Friend Shared ReadOnly Property PravidloKompozicionalni_Chyba_pri_nacitani_kompozicionalniho_pravidla_z_XML() As String
            Get
                Return ResourceManager.GetString("PravidloKompozicionalni_Chyba_pri_nacitani_kompozicionalniho_pravidla_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování kompozicionálního pravidla .
        '''</summary>
        Friend Shared ReadOnly Property PravidloKompozicionalni_Chyba_pri_propojovani_kompozicionalniho_pravidla() As String
            Get
                Return ResourceManager.GetString("PravidloKompozicionalni_Chyba_pri_propojovani_kompozicionalniho_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v pravidlu .
        '''</summary>
        Friend Shared ReadOnly Property PravidloKompozicionalni_Chyba_pri_SaveToXML_v_pravidlu() As String
            Get
                Return ResourceManager.GetString("PravidloKompozicionalni_Chyba_pri_SaveToXML_v_pravidlu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu kompozicionálního pravidla .
        '''</summary>
        Friend Shared ReadOnly Property pravidloKompozicionalni_Chyba_pri_tvorbe_vypisu_kompozicionalniho_pravidla() As String
            Get
                Return ResourceManager.GetString("pravidloKompozicionalni_Chyba_pri_tvorbe_vypisu_kompozicionalniho_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  : rule .
        '''</summary>
        Friend Shared ReadOnly Property PravidloKompozicionalni_pravidlo() As String
            Get
                Return ResourceManager.GetString("PravidloKompozicionalni_pravidlo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání logickeho pravidla z XML.
        '''</summary>
        Friend Shared ReadOnly Property PravidloLogicke_Chyba_pri_nacitani_logickeho_pravidla_z_XML() As String
            Get
                Return ResourceManager.GetString("PravidloLogicke_Chyba_pri_nacitani_logickeho_pravidla_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování logického pravidla .
        '''</summary>
        Friend Shared ReadOnly Property PravidloLogicke_Chyba_pri_propojovani_logickeho_pravidla() As String
            Get
                Return ResourceManager.GetString("PravidloLogicke_Chyba_pri_propojovani_logickeho_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v logickém pravidle .
        '''</summary>
        Friend Shared ReadOnly Property PravidloLogicke_Chyba_pri_SaveToXML_v_logickem_pravidle() As String
            Get
                Return ResourceManager.GetString("PravidloLogicke_Chyba_pri_SaveToXML_v_logickem_pravidle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu logického pravidla .
        '''</summary>
        Friend Shared ReadOnly Property PravidloLogicke_Chyba_pri_tvorbe_vypisu_logickeho_pravidla() As String
            Get
                Return ResourceManager.GetString("PravidloLogicke_Chyba_pri_tvorbe_vypisu_logickeho_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  : rule .
        '''</summary>
        Friend Shared ReadOnly Property PravidloLogicke_pravidlo() As String
            Get
                Return ResourceManager.GetString("PravidloLogicke_pravidlo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání předpokladu pravidla z XML.
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Chyba_pri_nacitani_predpokladu_pravidla_z_XML() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Chyba_pri_nacitani_predpokladu_pravidla_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování kontextu .
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Chyba_pri_propojovani_kontextu() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Chyba_pri_propojovani_kontextu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při propojování předpokladu u pravidla .
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Chyba_pri_propojovani_predpokladu_u_pravidla() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Chyba_pri_propojovani_predpokladu_u_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v předpokladu.
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Chyba_pri_SaveToXML_v_predpokladu() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Chyba_pri_SaveToXML_v_predpokladu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu předpokladu.
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Chyba_pri_tvorbe_vypisu_predpokladu() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Chyba_pri_tvorbe_vypisu_predpokladu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování předpokladu backward.
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Chyba_pri_vyhodnocovani_predpokladu_backward() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Chyba_pri_vyhodnocovani_predpokladu_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prázdný předpoklad pravidla.
        '''</summary>
        Friend Shared ReadOnly Property Predpoklad_Prazdny_predpoklad_pravidla() As String
            Get
                Return ResourceManager.GetString("Predpoklad_Prazdny_predpoklad_pravidla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Priority.
        '''</summary>
        Friend Shared ReadOnly Property Priorita() As String
            Get
                Return ResourceManager.GetString("Priorita", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání hodnot případu z atributu.
        '''</summary>
        Friend Shared ReadOnly Property Pripad_Chyba_pri_nacitani_hodnot_pripadu_z_atributu() As String
            Get
                Return ResourceManager.GetString("Pripad_Chyba_pri_nacitani_hodnot_pripadu_z_atributu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání Pripadu z XML.
        '''</summary>
        Friend Shared ReadOnly Property Pripad_Chyba_pri_nacitani_Pripadu_z_XML() As String
            Get
                Return ResourceManager.GetString("Pripad_Chyba_pri_nacitani_Pripadu_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v Pripadu.
        '''</summary>
        Friend Shared ReadOnly Property Pripad_Chyba_pri_SaveToXML_v_Pripadu() As String
            Get
                Return ResourceManager.GetString("Pripad_Chyba_pri_SaveToXML_v_Pripadu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nepodařilo se načíst xml dokument pro Případ.
        '''</summary>
        Friend Shared ReadOnly Property Pripad_Nepodarilo_se_nacist_xml_dokument_pro_Pripad() As String
            Get
                Return ResourceManager.GetString("Pripad_Nepodarilo_se_nacist_xml_dokument_pro_Pripad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scope - case.
        '''</summary>
        Friend Shared ReadOnly Property Rozsah() As String
            Get
                Return ResourceManager.GetString("Rozsah", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weight range.
        '''</summary>
        Friend Shared ReadOnly Property RozsahVah() As String
            Get
                Return ResourceManager.GetString("RozsahVah", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slope.
        '''</summary>
        Friend Shared ReadOnly Property Slope() As String
            Get
                Return ResourceManager.GetString("Slope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property Typ() As String
            Get
                Return ResourceManager.GetString("Typ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proposition.
        '''</summary>
        Friend Shared ReadOnly Property Vyrok() As String
            Get
                Return ResourceManager.GetString("Vyrok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání id výroku z xml.
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_nacitani_id_vyroku_z_xml() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_nacitani_id_vyroku_z_xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání výroku z XML.
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_nacitani_vyroku_z_XML() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_nacitani_vyroku_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při odvozování výroku backward: .
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_odvozovani_vyroku_backward() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_odvozovani_vyroku_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML ve výroku .
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_SaveToXML_ve_vyroku() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_SaveToXML_ve_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu výroku .
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_tvorbe_vypisu_vyroku() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_tvorbe_vypisu_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při určování pozice výroku .
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_urcovani_pozice_vyroku() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_urcovani_pozice_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování výroku backward .
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_vyhodnocovani_vyroku_backward() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_vyhodnocovani_vyroku_backward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vytváření implicitních zdrojů výroku .
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Chyba_pri_vytvareni_defaultnich_zdroju_vyroku() As String
            Get
                Return ResourceManager.GetString("Vyrok_Chyba_pri_vytvareni_defaultnich_zdroju_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Žádný zdroj nebyl uspěšně vyhodnocen.
        '''</summary>
        Friend Shared ReadOnly Property Vyrok_Zadny_zdroj_nebyl_uspesne_vyhodnocen() As String
            Get
                Return ResourceManager.GetString("Vyrok_Zadny_zdroj_nebyl_uspesne_vyhodnocen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání numerického výroku z XML.
        '''</summary>
        Friend Shared ReadOnly Property VyrokNumeric_Chyba_pri_nacitani_numeric_vyroku_z_XML() As String
            Get
                Return ResourceManager.GetString("VyrokNumeric_Chyba_pri_nacitani_numeric_vyroku_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML ve výroku .
        '''</summary>
        Friend Shared ReadOnly Property VyrokNumeric_Chyba_pri_SaveToXML_ve_vyroku() As String
            Get
                Return ResourceManager.GetString("VyrokNumeric_Chyba_pri_SaveToXML_ve_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu výroku .
        '''</summary>
        Friend Shared ReadOnly Property VyrokNumeric_Chyba_pri_tvorbe_vypisu_vyroku() As String
            Get
                Return ResourceManager.GetString("VyrokNumeric_Chyba_pri_tvorbe_vypisu_vyroku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Propositions.
        '''</summary>
        Friend Shared ReadOnly Property Vyroky() As String
            Get
                Return ResourceManager.GetString("Vyroky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání závěru pravidla z XML.
        '''</summary>
        Friend Shared ReadOnly Property Zaver_Chyba_pri_nacitani_zaveru_pravidla_z_XML() As String
            Get
                Return ResourceManager.GetString("Zaver_Chyba_pri_nacitani_zaveru_pravidla_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v závěru.
        '''</summary>
        Friend Shared ReadOnly Property Zaver_Chyba_pri_SaveToXML_v_zaveru() As String
            Get
                Return ResourceManager.GetString("Zaver_Chyba_pri_SaveToXML_v_zaveru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při tvorbě výpisu zaveru.
        '''</summary>
        Friend Shared ReadOnly Property Zaver_Chyba_pri_tvorbe_vypisu_zaveru() As String
            Get
                Return ResourceManager.GetString("Zaver_Chyba_pri_tvorbe_vypisu_zaveru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání cílů u zdroje CBR.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojCBR_Chyba_pri_nacitani_cilu_u_zdroje_CBR() As String
            Get
                Return ResourceManager.GetString("ZdrojCBR_Chyba_pri_nacitani_cilu_u_zdroje_CBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání vah atributu u zdroje CBR.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojCBR_Chyba_pri_nacitani_vah_atributu_u_zdroje_CBR() As String
            Get
                Return ResourceManager.GetString("ZdrojCBR_Chyba_pri_nacitani_vah_atributu_u_zdroje_CBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML ve zdroji CBR.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojCBR_Chyba_pri_SaveToXML_ve_zdroji_CBR() As String
            Get
                Return ResourceManager.GetString("ZdrojCBR_Chyba_pri_SaveToXML_ve_zdroji_CBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování zdroje CBR.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojCBR_Chyba_pri_vyhodnocovani_zdroje_CBR() As String
            Get
                Return ResourceManager.GetString("ZdrojCBR_Chyba_pri_vyhodnocovani_zdroje_CBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nepodařilo se načíst xml dokument pro zdroj CBR.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojCBR_Nepodarilo_se_nacist_xml_dokument_pro_zdroj_CBR() As String
            Get
                Return ResourceManager.GetString("ZdrojCBR_Nepodarilo_se_nacist_xml_dokument_pro_zdroj_CBR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sources.
        '''</summary>
        Friend Shared ReadOnly Property Zdroje() As String
            Get
                Return ResourceManager.GetString("Zdroje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání implicitní váhy z XML.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojImplicitniVaha_Chyba_pri_nacitani_implicitni_vahy_z_XML() As String
            Get
                Return ResourceManager.GetString("ZdrojImplicitniVaha_Chyba_pri_nacitani_implicitni_vahy_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML ve zdroji implicitni vaha.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojImplicitniVaha_Chyba_pri_SaveToXML_ve_zdroji_implicitni_vaha() As String
            Get
                Return ResourceManager.GetString("ZdrojImplicitniVaha_Chyba_pri_SaveToXML_ve_zdroji_implicitni_vaha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při vyhodnocování zdroje implicitní váha.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojImplicitniVaha_Chyba_pri_vyhodnocovani_zdroje_implicitni_vaha() As String
            Get
                Return ResourceManager.GetString("ZdrojImplicitniVaha_Chyba_pri_vyhodnocovani_zdroje_implicitni_vaha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba ve zdroji odvozování pro výrok .
        '''</summary>
        Friend Shared ReadOnly Property ZdrojOdvozovani_Chyba_ve_zdroji_odvozovani_pro_vyrok() As String
            Get
                Return ResourceManager.GetString("ZdrojOdvozovani_Chyba_ve_zdroji_odvozovani_pro_vyrok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atribut na vstupu členu výpočtu není numerický.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Atribut_na_vstupu_clenu_vypoctu_neni_numericky() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Atribut_na_vstupu_clenu_vypoctu_neni_numericky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání druhého vstupu výpočtu.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_nacitani_druheho_vstupu_vypoctu() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_nacitani_druheho_vstupu_vypoctu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání operandu.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_nacitani_operandu() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_nacitani_operandu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání prvního vstupu výpočtu.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_nacitani_prvniho_vstupu_vypoctu() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_nacitani_prvniho_vstupu_vypoctu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání výpočtu z XML.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_nacitani_vypoctu_z_XML() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_nacitani_vypoctu_z_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML v clenu vypoctu.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_SaveToXML_v_clenu_vypoctu() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_SaveToXML_v_clenu_vypoctu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při SaveToXML ve zdroji výpočet.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_SaveToXML_ve_zdroji_vypocet() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_SaveToXML_ve_zdroji_vypocet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při výpočtu členu.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_Chyba_pri_vypoctu_clenu() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_Chyba_pri_vypoctu_clenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vstup 1 není číslo!.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_vstup_1_neni_cislo() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_vstup_1_neni_cislo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vstup 2 není číslo!.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_vstup_2_neni_cislo() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_vstup_2_neni_cislo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to zadana vaha.
        '''</summary>
        Friend Shared ReadOnly Property ZdrojVypocet_zadana_vaha() As String
            Get
                Return ResourceManager.GetString("ZdrojVypocet_zadana_vaha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chyba při načítání CBR z XML.
        '''</summary>
        Friend Shared ReadOnly Property ZrojCBR_Chyba_pri_nacitani_CBR_z_XML() As String
            Get
                Return ResourceManager.GetString("ZrojCBR_Chyba_pri_nacitani_CBR_z_XML", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
