'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
'
Namespace nestws
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="NestWSSoap", [Namespace]:="http://tempuri.org/NestWS/NestWS"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BaseResult))>  _
    Partial Public Class NestWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RunConsultationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RunConsultationZipOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RunConsultationZip2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.NestFileClient.My.MySettings.Default.NestFileClient_nestws_NestWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RunConsultationCompleted As RunConsultationCompletedEventHandler
        
        '''<remarks/>
        Public Event RunConsultationZipCompleted As RunConsultationZipCompletedEventHandler
        
        '''<remarks/>
        Public Event RunConsultationZip2Completed As RunConsultationZip2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NestWS/NestWS/RunConsultation", RequestNamespace:="http://tempuri.org/NestWS/NestWS", ResponseNamespace:="http://tempuri.org/NestWS/NestWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunConsultation(ByVal BazeZnalostiXML As String, ByVal AnswersXML As String) As ConsultationResult
            Dim results() As Object = Me.Invoke("RunConsultation", New Object() {BazeZnalostiXML, AnswersXML})
            Return CType(results(0),ConsultationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RunConsultationAsync(ByVal BazeZnalostiXML As String, ByVal AnswersXML As String)
            Me.RunConsultationAsync(BazeZnalostiXML, AnswersXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RunConsultationAsync(ByVal BazeZnalostiXML As String, ByVal AnswersXML As String, ByVal userState As Object)
            If (Me.RunConsultationOperationCompleted Is Nothing) Then
                Me.RunConsultationOperationCompleted = AddressOf Me.OnRunConsultationOperationCompleted
            End If
            Me.InvokeAsync("RunConsultation", New Object() {BazeZnalostiXML, AnswersXML}, Me.RunConsultationOperationCompleted, userState)
        End Sub
        
        Private Sub OnRunConsultationOperationCompleted(ByVal arg As Object)
            If (Not (Me.RunConsultationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RunConsultationCompleted(Me, New RunConsultationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NestWS/NestWS/RunConsultationZip", RequestNamespace:="http://tempuri.org/NestWS/NestWS", ResponseNamespace:="http://tempuri.org/NestWS/NestWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunConsultationZip(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal BazeZnalostiZip() As Byte) As ConsultationResult
            Dim results() As Object = Me.Invoke("RunConsultationZip", New Object() {BazeZnalostiZip})
            Return CType(results(0),ConsultationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RunConsultationZipAsync(ByVal BazeZnalostiZip() As Byte)
            Me.RunConsultationZipAsync(BazeZnalostiZip, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RunConsultationZipAsync(ByVal BazeZnalostiZip() As Byte, ByVal userState As Object)
            If (Me.RunConsultationZipOperationCompleted Is Nothing) Then
                Me.RunConsultationZipOperationCompleted = AddressOf Me.OnRunConsultationZipOperationCompleted
            End If
            Me.InvokeAsync("RunConsultationZip", New Object() {BazeZnalostiZip}, Me.RunConsultationZipOperationCompleted, userState)
        End Sub
        
        Private Sub OnRunConsultationZipOperationCompleted(ByVal arg As Object)
            If (Not (Me.RunConsultationZipCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RunConsultationZipCompleted(Me, New RunConsultationZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NestWS/NestWS/RunConsultationZip2", RequestNamespace:="http://tempuri.org/NestWS/NestWS", ResponseNamespace:="http://tempuri.org/NestWS/NestWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunConsultationZip2(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal BazeZnalostiZip() As Byte, ByVal AnswersXML As String) As ConsultationResult
            Dim results() As Object = Me.Invoke("RunConsultationZip2", New Object() {BazeZnalostiZip, AnswersXML})
            Return CType(results(0),ConsultationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RunConsultationZip2Async(ByVal BazeZnalostiZip() As Byte, ByVal AnswersXML As String)
            Me.RunConsultationZip2Async(BazeZnalostiZip, AnswersXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RunConsultationZip2Async(ByVal BazeZnalostiZip() As Byte, ByVal AnswersXML As String, ByVal userState As Object)
            If (Me.RunConsultationZip2OperationCompleted Is Nothing) Then
                Me.RunConsultationZip2OperationCompleted = AddressOf Me.OnRunConsultationZip2OperationCompleted
            End If
            Me.InvokeAsync("RunConsultationZip2", New Object() {BazeZnalostiZip, AnswersXML}, Me.RunConsultationZip2OperationCompleted, userState)
        End Sub
        
        Private Sub OnRunConsultationZip2OperationCompleted(ByVal arg As Object)
            If (Not (Me.RunConsultationZip2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RunConsultationZip2Completed(Me, New RunConsultationZip2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/NestWS/NestWS")>  _
    Partial Public Class ConsultationResult
        Inherits BaseResult
        
        Private resultXMLField As String
        
        '''<remarks/>
        Public Property ResultXML() As String
            Get
                Return Me.resultXMLField
            End Get
            Set
                Me.resultXMLField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ConsultationResult)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/NestWS/NestWS")>  _
    Partial Public Class BaseResult
        
        Private isOKField As Boolean
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property isOK() As Boolean
            Get
                Return Me.isOKField
            End Get
            Set
                Me.isOKField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub RunConsultationCompletedEventHandler(ByVal sender As Object, ByVal e As RunConsultationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RunConsultationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultationResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub RunConsultationZipCompletedEventHandler(ByVal sender As Object, ByVal e As RunConsultationZipCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RunConsultationZipCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultationResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub RunConsultationZip2CompletedEventHandler(ByVal sender As Object, ByVal e As RunConsultationZip2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RunConsultationZip2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultationResult)
            End Get
        End Property
    End Class
End Namespace
